import type { OptionMetaItem } from './types';

export const barOptionMeta: OptionMetaItem[] = [
  {
    path: 'width',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布宽度（px）。',
  },
  {
    path: 'height',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布高度（px）。',
  },
  {
    path: 'padding',
    type: 'number | {top,right,bottom,left}',
    group: 'Base',
    defaultToken: 'chartTokens.spacing.chartPadding',
    description: '图表内边距，影响坐标系布局与标签预留空间。',
  },
  {
    path: 'animationDuration',
    type: 'number',
    group: 'Base',
    defaultValue: '0',
    description: '动画时长（ms）。',
  },
  {
    path: 'interaction.enabled',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否启用交互（hover 竖线/高亮/tooltip）。',
  },
  {
    path: 'interaction.axisPointer.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 hover 竖向指示线。',
  },
  {
    path: 'interaction.tooltip.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 tooltip 浮窗。',
  },
  {
    path: 'interaction.tooltip.formatter',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 内容自定义格式化；values[0] 为当前柱子值。',
  },
  {
    path: 'interaction.tooltip.render',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 自定义渲染，返回任意 ReactNode（可传入自定义布局）。',
  },
  {
    path: 'x.labels',
    type: 'string[]',
    group: 'X Axis',
    defaultValue: 'auto',
    description: 'x 轴标签，不传则用 1..N 占位。',
  },
  {
    path: 'y.min',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴下界；不传则自动推导并 padding。',
  },
  {
    path: 'y.max',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴上界；不传则自动推导并 padding。',
  },
  {
    path: 'y.splitNum',
    type: 'number',
    group: 'Y Axis',
    defaultToken: 'chartTokens.axis.ySplitNum',
    description: 'y 轴分段数（产生 splitNum+1 个刻度）。',
  },
  {
    path: 'y.splitLine.show',
    type: 'boolean',
    group: 'Y Axis',
    defaultValue: 'true',
    description: '是否显示 y 轴分割线（横向网格线）。',
  },
  {
    path: 'series',
    type: 'BarSeries | BarSeries[]',
    group: 'Series',
    defaultValue: '-',
    description: '柱状序列配置；传数组可绘制多组柱状（配合 shift 做分组）。',
  },
  {
    path: 'series[]',
    type: 'BarSeries',
    group: 'Series',
    defaultValue: 'undefined',
    description: '多组柱状序列数组元素。',
  },
  {
    path: 'series.values',
    type: 'number[]',
    group: 'Series',
    defaultValue: '-',
    description: '柱状数据值序列。',
  },
  {
    path: 'series.colors',
    type: 'string | string[]',
    group: 'Series',
    defaultToken: 'chartTokens.color.chart.bar',
    description: '柱子颜色；数组时按索引取色。',
  },
  {
    path: 'series.barWidth',
    type: 'number',
    group: 'Series',
    defaultValue: 'auto',
    description: '柱宽（px）。不传则按间距自动计算。',
  },
  {
    path: 'series.radius',
    type: 'number',
    group: 'Series',
    defaultToken: 'chartTokens.shape.radius.bar',
    description: '圆角半径（px）。',
  },
  {
    path: 'series.shift',
    type: 'number',
    group: 'Series',
    defaultValue: '0',
    description: '整体水平偏移（px）。',
  },
  {
    path: 'series.labels',
    type: 'boolean',
    group: 'Label',
    defaultValue: 'false',
    description: '是否绘制柱顶部/底部数值标签。',
  },
  {
    path: 'series.labelFormatter',
    type: '(v:number) => string | number',
    group: 'Label',
    defaultValue: '(v) => v',
    description: '标签格式化函数。',
  },
  {
    path: 'series.labelColor',
    type: 'string',
    group: 'Label',
    defaultToken: 'chartTokens.color.text.secondary',
    description: '标签颜色。',
  },
  {
    path: 'series.labelFontSize',
    type: 'number',
    group: 'Label',
    defaultToken: 'chartTokens.typography.fontSize.axis',
    description: '标签字号（px）。',
  },
  {
    path: 'series.labelGap',
    type: 'number | number[]',
    group: 'Label',
    defaultToken: 'chartTokens.spacing.label.gap',
    description: '标签与柱子的间距（px）。',
  },
  {
    path: 'series.zero',
    type: 'number',
    group: 'Series',
    defaultValue: 'yAxis.min',
    description: '零基线值；不传则取 y 轴下界。',
  },
];
