import type { OptionMetaItem } from './types';

export const candleOptionMeta: OptionMetaItem[] = [
  {
    path: 'width',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布宽度（px）。',
  },
  {
    path: 'height',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布高度（px）。',
  },
  {
    path: 'padding',
    type: 'number | {top,right,bottom,left}',
    group: 'Base',
    defaultToken: 'chartTokens.spacing.chartPadding',
    description: '图表内边距，影响坐标系布局与标签预留空间。',
  },
  {
    path: 'animationDuration',
    type: 'number',
    group: 'Base',
    defaultValue: '0',
    description: '动画时长（ms）。',
  },
  {
    path: 'interaction.enabled',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否启用交互（hover 竖线/高亮/tooltip）。',
  },
  {
    path: 'interaction.axisPointer.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 hover 竖向指示线。',
  },
  {
    path: 'interaction.tooltip.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 tooltip 浮窗。',
  },
  {
    path: 'interaction.tooltip.formatter',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 内容自定义格式化；values 为当前 K 线的 [open, close, low, high]。',
  },
  {
    path: 'interaction.tooltip.render',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 自定义渲染，返回任意 ReactNode（可传入自定义布局）。',
  },
  {
    path: 'x.labels',
    type: 'string[]',
    group: 'X Axis',
    defaultValue: 'auto',
    description: 'x 轴标签，不传则用 1..N 占位。',
  },
  {
    path: 'y.min',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴下界；不传则自动推导并 padding。',
  },
  {
    path: 'y.max',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴上界；不传则自动推导并 padding。',
  },
  {
    path: 'y.splitNum',
    type: 'number',
    group: 'Y Axis',
    defaultToken: 'chartTokens.axis.ySplitNum',
    description: 'y 轴分段数（产生 splitNum+1 个刻度）。',
  },
  {
    path: 'y.splitLine.show',
    type: 'boolean',
    group: 'Y Axis',
    defaultValue: 'true',
    description: '是否显示 y 轴分割线（横向网格线）。',
  },
  {
    path: 'series',
    type: 'CandleSeries',
    group: 'Series',
    defaultValue: '-',
    description: 'K 线序列配置。',
  },
  {
    path: 'series.values',
    type: 'Array<[open, close, low, high]>',
    group: 'Series',
    defaultValue: '-',
    description: 'K 线 OHLC 数据数组。',
  },
  {
    path: 'series.candleWidth',
    type: 'number',
    group: 'Series',
    defaultValue: 'auto',
    description: 'K 线实体宽度（px）。不传则按间距自动计算。',
  },
  {
    path: 'series.rise.fill',
    type: 'string',
    group: 'Style',
    defaultToken: 'chartTokens.color.chart.positive',
    description: '上涨实体填充色。',
  },
  {
    path: 'series.rise.border',
    type: 'string',
    group: 'Style',
    defaultToken: 'chartTokens.color.chart.positive',
    description: '上涨边框色。',
  },
  {
    path: 'series.fall.fill',
    type: 'string',
    group: 'Style',
    defaultToken: 'chartTokens.color.chart.negative',
    description: '下跌实体填充色。',
  },
  {
    path: 'series.fall.border',
    type: 'string',
    group: 'Style',
    defaultToken: 'chartTokens.color.chart.negative',
    description: '下跌边框色。',
  },
];
