import type { OptionMetaItem } from './types';

export const lineOptionMeta: OptionMetaItem[] = [
  {
    path: 'width',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布宽度（px）。',
    example: '{ width: 360 }',
  },
  {
    path: 'height',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布高度（px）。',
    example: '{ height: 200 }',
  },
  {
    path: 'padding',
    type: 'number | {top,right,bottom,left}',
    group: 'Base',
    defaultToken: 'chartTokens.spacing.chartPadding',
    description: '图表内边距，影响坐标系布局与标签预留空间。',
    example: '{ padding: 12 }',
  },
  {
    path: 'animationDuration',
    type: 'number',
    group: 'Base',
    defaultValue: '0',
    description: '折线绘制动画时长（ms）。0 表示不启用裁剪动画。',
    example: '{ animationDuration: 600 }',
  },
  {
    path: 'interaction.enabled',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否启用交互（hover 竖线/高亮/tooltip）。',
    example: '{ interaction: { enabled: false } }',
  },
  {
    path: 'interaction.axisPointer.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 hover 竖向指示线。',
    example: '{ interaction: { axisPointer: { show: false } } }',
  },
  {
    path: 'interaction.tooltip.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 tooltip 浮窗。',
    example: '{ interaction: { tooltip: { show: false } } }',
  },
  {
    path: 'interaction.tooltip.formatter',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 内容自定义格式化；values 为所有 series 在当前 index 的值数组。',
    example:
      '{ interaction: { tooltip: { formatter: ({ xLabel, values }) => `${xLabel}: ${values[0]}` } } }',
  },
  {
    path: 'interaction.tooltip.render',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 自定义渲染，返回任意 ReactNode（可传入自定义布局）。',
    example:
      '{ interaction: { tooltip: { render: ({ xLabel, values }) => <div><b>{xLabel}</b> {values[0]}</div> } } }',
  },
  {
    path: 'x.labels',
    type: 'string[]',
    group: 'X Axis',
    defaultValue: 'auto',
    description: 'x 轴标签，长度建议与数据点数一致；不传则用 1..N 占位。',
    example: "{ x: { labels: ['D1','D2'] } }",
  },
  {
    path: 'x.fontSize',
    type: 'number',
    group: 'X Axis',
    defaultToken: 'chartTokens.typography.fontSize.axis',
    description: 'x 轴文本字号（px）。',
    example: '{ x: { fontSize: 12 } }',
  },
  {
    path: 'x.color',
    type: 'string',
    group: 'X Axis',
    defaultToken: 'chartTokens.color.text.secondary',
    description: 'x 轴文本颜色。',
    example: "{ x: { color: '#333' } }",
  },
  {
    path: 'x.margin',
    type: 'number',
    group: 'X Axis',
    defaultToken: 'chartTokens.spacing.axis.xLabelMargin',
    description: 'x 轴标签与坐标系的间距（px）。',
    example: '{ x: { margin: 6 } }',
  },
  {
    path: 'y.min',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴下界；不传则从数据自动推导并 padding。',
    example: '{ y: { min: 0 } }',
  },
  {
    path: 'y.max',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴上界；不传则从数据自动推导并 padding。',
    example: '{ y: { max: 100 } }',
  },
  {
    path: 'y.splitNum',
    type: 'number',
    group: 'Y Axis',
    defaultToken: 'chartTokens.axis.ySplitNum',
    description: 'y 轴分段数（产生 splitNum+1 个刻度）。',
    example: '{ y: { splitNum: 4 } }',
  },
  {
    path: 'y.splitLine.show',
    type: 'boolean',
    group: 'Y Axis',
    defaultValue: 'true',
    description: '是否显示 y 轴分割线（横向网格线）。',
    example: '{ y: { splitLine: { show: false } } }',
  },
  {
    path: 'y.align',
    type: "'left' | 'right'",
    group: 'Y Axis',
    defaultValue: "'right'",
    description: 'y 轴标签对齐方式。',
    example: "{ y: { align: 'left' } }",
  },
  {
    path: 'y.labelFormatter',
    type: '(v:number, index?:number) => string | number',
    group: 'Y Axis',
    defaultValue: '(v) => v',
    description: 'y 轴刻度格式化函数。',
    example: '{ y: { labelFormatter: (v) => `${v}%` } }',
  },
  {
    path: 'series',
    type: 'LineSeries | LineSeries[]',
    group: 'Series',
    defaultValue: '-',
    description: '折线序列，单条或多条。',
  },
  {
    path: 'series.values',
    type: 'Array<number | undefined>',
    group: 'Series',
    defaultValue: '-',
    description: '数据点序列；undefined/NaN 会断开折线段。',
    example: '{ series: { values: [1, 2, undefined, 4] } }',
  },
  {
    path: 'series.smooth',
    type: 'number',
    group: 'Series',
    defaultValue: '0',
    description: '平滑系数（0 表示折线，>0 表示曲线）。',
    example: '{ series: { smooth: 0.2 } }',
  },
  {
    path: 'series.color',
    type: 'string',
    group: 'Series',
    defaultToken: 'chartTokens.color.chart.line',
    description: '折线颜色。',
    example: "{ series: { color: '#f00' } }",
  },
  {
    path: 'series.width',
    type: 'number',
    group: 'Series',
    defaultToken: 'chartTokens.stroke.width.line',
    description: '折线宽度（px）。',
    example: '{ series: { width: 2 } }',
  },
  {
    path: 'series.dash',
    type: 'string',
    group: 'Series',
    defaultValue: 'undefined',
    description: '虚线样式（SVG strokeDasharray）。',
    example: "{ series: { dash: '4 2' } }",
  },
  {
    path: 'series.area',
    type: '{ start: string; end: string }',
    group: 'Series',
    defaultValue: 'undefined',
    description: '折线下方渐变填充；start/end 为颜色字符串（支持 rgba）。',
    example: '{ series: { area: { start: "rgba(240,65,66,0.25)", end: "rgba(240,65,66,0)" } } }',
  },
  {
    path: 'series.lineStyle.zeroValue',
    type: 'number',
    group: 'Series',
    defaultValue: '0',
    description: '分段渲染的基准线值（用于上下分色与填充闭合线）。',
    example: '{ series: { lineStyle: { zeroValue: 0 } } }',
  },
  {
    path: 'series.lineStyle.segmentColor',
    type: '{ above: string; below: string }',
    group: 'Series',
    defaultValue: 'undefined',
    description: '基准线上/下分段线色。',
    example: '{ series: { lineStyle: { segmentColor: { above: "#f04142", below: "#2da822" } } } }',
  },
  {
    path: 'series.lineStyle.segmentArea',
    type: '{ above: {start,end}; below: {start,end} }',
    group: 'Series',
    defaultValue: 'undefined',
    description: '折线与基准线之间的分段渐变填充（上/下使用不同渐变）。',
    example:
      '{ series: { lineStyle: { segmentArea: { above: { start: "rgba(240,65,66,0.16)", end: "rgba(240,65,66,0)" }, below: { start: "rgba(45,168,34,0)", end: "rgba(45,168,34,0.16)" } } } } }',
  },
  {
    path: 'series.points',
    type: 'boolean',
    group: 'Series',
    defaultValue: 'false',
    description: '是否绘制数据点圆点。',
    example: '{ series: { points: true } }',
  },
  {
    path: 'series.pointSize',
    type: 'number',
    group: 'Series',
    defaultToken: 'chartTokens.size.point',
    description: '数据点圆点直径（px）。',
    example: '{ series: { points: true, pointSize: 6 } }',
  },
];
