import type { OptionMetaItem } from './types';

export const multiOptionMeta: OptionMetaItem[] = [
  {
    path: 'width',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布宽度（px）。',
  },
  {
    path: 'height',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布高度（px）。',
  },
  {
    path: 'padding',
    type: 'number | {top,right,bottom,left}',
    group: 'Base',
    defaultToken: 'chartTokens.spacing.chartPadding',
    description: '图表内边距，影响坐标系布局与标签预留空间。',
  },
  {
    path: 'animationDuration',
    type: 'number',
    group: 'Base',
    defaultValue: '0',
    description: '动画时长（ms）。',
  },
  {
    path: 'interaction.enabled',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否启用交互（hover 竖线/高亮/tooltip）。',
  },
  {
    path: 'interaction.axisPointer.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 hover 竖向指示线。',
  },
  {
    path: 'interaction.tooltip.show',
    type: 'boolean',
    group: 'Interaction',
    defaultValue: 'true',
    description: '是否显示 tooltip 浮窗。',
  },
  {
    path: 'interaction.tooltip.formatter',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 内容自定义格式化；MultiChart 默认会展示每个 series 的当前值。',
  },
  {
    path: 'interaction.tooltip.render',
    type: '({ index, xLabel, values }) => ReactNode',
    group: 'Interaction',
    defaultValue: 'undefined',
    description: 'tooltip 自定义渲染，返回任意 ReactNode（可传入自定义布局）。',
  },
  {
    path: 'x.labels',
    type: 'string[]',
    group: 'X Axis',
    defaultValue: 'auto',
    description: 'x 轴标签，不传则用 1..N 占位。',
  },
  {
    path: 'y.min',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴下界；不传则自动推导并 padding。',
  },
  {
    path: 'y.max',
    type: 'number',
    group: 'Y Axis',
    defaultValue: 'auto(extent(values))',
    description: 'y 轴上界；不传则自动推导并 padding。',
  },
  {
    path: 'y.splitNum',
    type: 'number',
    group: 'Y Axis',
    defaultToken: 'chartTokens.axis.ySplitNum',
    description: 'y 轴分段数（产生 splitNum+1 个刻度）。',
  },
  {
    path: 'y.splitLine.show',
    type: 'boolean',
    group: 'Y Axis',
    defaultValue: 'true',
    description: '是否显示 y 轴分割线（横向网格线）。',
  },
  {
    path: 'series',
    type: 'MultiSeries[]',
    group: 'Series',
    defaultValue: '-',
    description: '混合序列数组（line/bar/candle）。',
  },
  {
    path: 'series[].type',
    type: "'line' | 'bar' | 'candle'",
    group: 'Series',
    defaultValue: '-',
    description: '系列类型。',
  },
  {
    path: 'series[].(line).values',
    type: 'Array<number | undefined>',
    group: 'Line',
    defaultValue: '-',
    description: '折线数据；undefined/NaN 会断开折线段。',
  },
  {
    path: 'series[].(line).smooth',
    type: 'number',
    group: 'Line',
    defaultValue: '0',
    description: '平滑系数（0 表示折线）。',
  },
  {
    path: 'series[].(line).color',
    type: 'string',
    group: 'Line',
    defaultToken: 'chartTokens.color.chart.line',
    description: '折线颜色。',
  },
  {
    path: 'series[].(line).width',
    type: 'number',
    group: 'Line',
    defaultToken: 'chartTokens.stroke.width.line',
    description: '折线宽度（px）。',
  },
  {
    path: 'series[].(line).lineStyle.zeroValue',
    type: 'number',
    group: 'Line',
    defaultValue: '0',
    description: '分段渲染的基准线值（用于上下分色与填充闭合线）。',
  },
  {
    path: 'series[].(line).lineStyle.segmentColor',
    type: '{ above: string; below: string }',
    group: 'Line',
    defaultValue: 'undefined',
    description: '基准线上/下分段线色。',
  },
  {
    path: 'series[].(line).lineStyle.segmentArea',
    type: '{ above: {start,end}; below: {start,end} }',
    group: 'Line',
    defaultValue: 'undefined',
    description: '折线与基准线之间的分段渐变填充（上/下使用不同渐变）。',
  },
  {
    path: 'series[].(line).points',
    type: 'boolean',
    group: 'Line',
    defaultValue: 'false',
    description: '是否绘制数据点圆点。',
  },
  {
    path: 'series[].(line).pointSize',
    type: 'number',
    group: 'Line',
    defaultToken: 'chartTokens.size.point',
    description: '数据点圆点直径（px）。',
  },
  {
    path: 'series[].(bar).barWidth',
    type: 'number',
    group: 'Bar',
    defaultValue: 'auto',
    description: '柱子宽度（px）。不传则按间距自动计算。',
  },
  {
    path: 'series[].(bar).values',
    type: 'number[]',
    group: 'Bar',
    defaultValue: '-',
    description: '柱状数据值序列。',
  },
  {
    path: 'series[].(bar).colors',
    type: 'string | string[]',
    group: 'Bar',
    defaultToken: 'chartTokens.color.chart.bar',
    description: '柱子颜色；数组时按索引取色。',
  },
  {
    path: 'series[].(bar).radius',
    type: 'number',
    group: 'Bar',
    defaultToken: 'chartTokens.shape.radius.bar',
    description: '圆角半径（px）。',
  },
  {
    path: 'series[].(bar).shift',
    type: 'number',
    group: 'Bar',
    defaultValue: '0',
    description: '整体水平偏移（px），用于分组柱状（barShift）。',
  },
  {
    path: 'series[].(bar).labels',
    type: 'boolean',
    group: 'Bar',
    defaultValue: 'false',
    description: '是否绘制标签。',
  },
  {
    path: 'series[].(bar).labelGap',
    type: 'number | number[]',
    group: 'Bar',
    defaultToken: 'chartTokens.spacing.label.gap',
    description: '标签与柱子的间距（px）。',
  },
  {
    path: 'series[].(bar).zero',
    type: 'number',
    group: 'Bar',
    defaultValue: 'yAxis.min',
    description: '零基线值；不传则取 y 轴下界。',
  },
  {
    path: 'series[].(candle).values',
    type: 'Array<[open, close, low, high]>',
    group: 'Candle',
    defaultValue: '-',
    description: 'K 线 OHLC 数据数组。',
  },
  {
    path: 'series[].(candle).rise.fill',
    type: 'string',
    group: 'Candle',
    defaultToken: 'chartTokens.color.chart.positive',
    description: '上涨实体填充色。',
  },
  {
    path: 'series[].(candle).fall.fill',
    type: 'string',
    group: 'Candle',
    defaultToken: 'chartTokens.color.chart.negative',
    description: '下跌实体填充色。',
  },
];
