import type { OptionMetaItem } from './types';

export const radarOptionMeta: OptionMetaItem[] = [
  {
    path: 'width',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布宽度（px）。',
  },
  {
    path: 'height',
    type: 'number',
    group: 'Base',
    defaultValue: '-',
    description: '画布高度（px）。',
  },
  {
    path: 'shape',
    type: "'polygon' | 'circle'",
    group: 'Base',
    defaultValue: "'polygon'",
    description: '网格形状：多边形或圆形。',
  },
  {
    path: 'padding',
    type: 'number | {top,right,bottom,left}',
    group: 'Base',
    defaultToken: 'chartTokens.spacing.chartPadding',
    description: '图表内边距，影响雷达半径与文字布局。',
  },
  {
    path: 'splitNumber',
    type: 'number',
    group: 'Grid',
    defaultValue: '3',
    description: '网格分段数。',
  },
  {
    path: 'indicator',
    type: 'Array<{ text: string | string[]; max: number; shiftX?: number; shiftY?: number }>',
    group: 'Indicator',
    defaultValue: '-',
    description: '维度配置：文本/最大值/微调偏移。',
  },
  {
    path: 'indicatorStyle.fontSize',
    type: 'number',
    group: 'Indicator',
    defaultToken: 'chartTokens.typography.fontSize.axis',
    description: '指标文本字号（px）。',
  },
  {
    path: 'indicatorStyle.fontColor',
    type: 'string',
    group: 'Indicator',
    defaultToken: 'chartTokens.color.text.secondary',
    description: '指标文本颜色。',
  },
  {
    path: 'indicatorStyle.gap',
    type: 'number',
    group: 'Indicator',
    defaultToken: 'chartTokens.spacing.radar.indicatorGap',
    description: '指标文本与顶点的间距（px）。',
  },
  {
    path: 'splitLine.width',
    type: 'number',
    group: 'Grid',
    defaultToken: 'chartTokens.stroke.width.axisLine',
    description: '网格分割线宽度（px）。',
  },
  {
    path: 'splitLine.color',
    type: 'string',
    group: 'Grid',
    defaultToken: 'chartTokens.color.grid.line',
    description: '网格分割线颜色。',
  },
  {
    path: 'splitLine.dash',
    type: 'string',
    group: 'Grid',
    defaultValue: 'undefined',
    description: '网格分割线虚线（SVG strokeDasharray）。',
  },
  {
    path: 'splitArea.color',
    type: 'string[]',
    group: 'Grid',
    defaultValue: 'undefined',
    description: '网格分割区域的交替背景色。',
  },
  {
    path: 'axisLine.show',
    type: 'boolean',
    group: 'Axis',
    defaultValue: 'true',
    description: '是否绘制从中心指向顶点的轴线。',
  },
  {
    path: 'axisLine.width',
    type: 'number',
    group: 'Axis',
    defaultToken: 'chartTokens.stroke.width.axisLine',
    description: '轴线宽度（px）。',
  },
  {
    path: 'axisLine.color',
    type: 'string',
    group: 'Axis',
    defaultToken: 'chartTokens.color.chart.axisLine',
    description: '轴线颜色。',
  },
  {
    path: 'axisLine.dash',
    type: 'string',
    group: 'Axis',
    defaultValue: 'undefined',
    description: '轴线虚线（SVG strokeDasharray）。',
  },
  {
    path: 'dataset',
    type: 'Array<{ values: number[]; areaColor?: string; lineStyle?: {...}; symbol?: {...} }>',
    group: 'Series',
    defaultValue: '-',
    description: '雷达数据集数组。',
  },
  {
    path: 'dataset[].values',
    type: 'number[]',
    group: 'Series',
    defaultValue: '-',
    description: '每个维度的取值数组（长度需与 indicator 一致）。',
  },
  {
    path: 'dataset[].areaColor',
    type: 'string',
    group: 'Series',
    defaultValue: 'undefined',
    description: '面积填充颜色（支持 rgba）。',
  },
  {
    path: 'dataset[].lineStyle.color',
    type: 'string',
    group: 'Series',
    defaultToken: 'chartTokens.color.chart.radar',
    description: '轮廓线颜色。',
  },
];
